name: learn-github-actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.14'
          
      - name: Setup go tools
        run: |
          go version
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest    
          
      - name: Run Subfinder
        run: subfinder -silent -d xsolla.com -o subfinder.txt
