name: Reconnaissance Workflow

on:
  push:
    branches:
      - main # adjust the branch as needed
  workflow_dispatch:

jobs:
  reconnaissance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'

      - name: Install Subfinder, HTTPX, and Nuclei
        run: |
          go get -u github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -u github.com/projectdiscovery/httpx/cmd/httpx
          go get -u github.com/projectdiscovery/nuclei/v2/cmd/nuclei

      - name: Subfinder Scan
        run: subfinder -silent -d example.com -o reports/subdomains.txt

      - name: HTTPX Scan
        run: cat reports/subdomains.txt | httpx -o reports/httpx_output.txt

      - name: Nuclei Scan
        run: nuclei -l reports/httpx_output.txt -o reports/nuclei_output.txt -stats
