name: Daily Amass Scan

on:
  schedule:
    - cron: '0 0 * * *' # Schedule the workflow to run daily at midnight

jobs:
  amass-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Amass
        run: |
          sudo apt-get update
          sudo apt-get install -y amass

      - name: Run Amass
        run: amass enum -d example.com -o reports/amass_output.txt
