name: Nuclei - Vulnerability Scan

on:
  workflow_dispatch:
  
jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://example.com


      - name: Upload Scan Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-log
          path: ${{ github.workspace }}/output/nuclei.log
